/* AL-ANDALOS RIJSCHOOL — MASTER CONTROL CENTER */
function controlCenterHtml(){return HtmlService.createHtmlOutputFromFile('ControlCenter').setTitle('Al-Andalos — Master Control Center').setXFrameOptionsMode(HtmlService.XFrameOptionsMode.ALLOWALL);}
function controlCenterOpen(){SpreadsheetApp.getUi().showSidebar(HtmlService.createHtmlOutputFromFile('ControlCenter').setTitle('Al-Andalos Control Center'));}
function controlCenterGetData(){const ss=SpreadsheetApp.getActiveSpreadsheet();return {generatedAt:new Date().toISOString(),dashboard:controlCenterDashboard_(ss),students:controlCenterRows_(ss,'Students'),lessons:controlCenterRows_(ss,'Bookings'),trainers:controlCenterRows_(ss,'Trainers'),packages:controlCenterRows_(ss,'Packages'),invoices:controlCenterRows_(ss,'Invoices'),payments:controlCenterRows_(ss,'WalletTransactions'),notifications:controlCenterRows_(ss,'Notifications')};}
function controlCenterDashboard_(ss){const students=controlCenterRows_(ss,'Students'),lessons=controlCenterRows_(ss,'Bookings'),payments=controlCenterRows_(ss,'WalletTransactions'),invoices=controlCenterRows_(ss,'Invoices');const today=controlCenterDateKey_(new Date()),month=Utilities.formatDate(new Date(),Session.getScriptTimeZone(),'yyyy-MM');const activeStudents=students.filter(r=>{const s=String(r.status||'').toLowerCase();return !s||['active','actief','true'].includes(s);}).length;const todayLessons=lessons.filter(r=>controlCenterDateKey_(r.date)===today).length;const upcomingLessons=lessons.filter(r=>controlCenterDateKey_(r.date)>=today).length;const revenue=payments.reduce((sum,r)=>{const d=controlCenterDateKey_(r.date||r.timestamp),a=Number(r.amount||0);return d.startsWith(month)&&a>0?sum+a:sum;},0);const outstanding=students.reduce((sum,r)=>{const b=Number(r.balance||0);return b<0?sum+Math.abs(b):sum;},0);return {totalStudents:students.length,activeStudents,todayLessons,upcomingLessons,monthlyRevenue:revenue,outstandingBalance:outstanding,totalInvoices:invoices.length,lastSync:new Date().toISOString()};}
function controlCenterRows_(ss,sheetName){const sh=ss.getSheetByName(sheetName);if(!sh||sh.getLastRow()<1)return [];const values=sh.getDataRange().getValues(),headers=values[0].map(h=>String(h||'').trim());return values.slice(1).filter(row=>row.some(v=>v!=='')).map((row,index)=>{const obj={_row:index+2,_sheet:sheetName};headers.forEach((h,i)=>{if(h)obj[h]=row[i];});obj.id=controlCenterFirst_(obj,['ID','Id','id','Student ID','Booking ID','Invoice ID','Transaction ID']);obj.studentId=controlCenterFirst_(obj,['Student ID','studentId','student_id']);obj.name=controlCenterFirst_(obj,['Name','Student Name','studentName','Full Name']);obj.email=controlCenterFirst_(obj,['Email','email','Email Address']);obj.phone=controlCenterFirst_(obj,['Phone','phone','Telephone']);obj.date=controlCenterFirst_(obj,['Date','date','Lesson Date','Invoice Date','Transaction Date']);obj.time=controlCenterFirst_(obj,['Time','time','Lesson Time']);obj.status=controlCenterFirst_(obj,['Status','status']);obj.amount=controlCenterFirst_(obj,['Amount','amount','Price','Total']);obj.balance=controlCenterFirst_(obj,['Balance','balance','Outstanding']);return obj;});}
function controlCenterFirst_(obj,keys){for(const k of keys)if(Object.prototype.hasOwnProperty.call(obj,k)&&obj[k]!=='')return obj[k];return '';}
function controlCenterDateKey_(value){if(!value)return '';const d=value instanceof Date?value:new Date(value);if(isNaN(d.getTime()))return String(value).slice(0,10);return Utilities.formatDate(d,Session.getScriptTimeZone(),'yyyy-MM-dd');}
function controlCenterCreateStudent(data){if(!data||!String(data.name||'').trim())throw new Error('Student name is required.');if(typeof createStudent==='function')return createStudent(data);throw new Error('createStudent() is not available.');}
function controlCenterCreateBooking(data){if(!data||!data.studentId)throw new Error('Student ID is required.');if(!data.date)throw new Error('Lesson date is required.');if(typeof apiCreateBooking==='function')return apiCreateBooking(data);throw new Error('apiCreateBooking() is not available.');}
function controlCenterAddDeposit(data){if(!data||!data.studentId)throw new Error('Student ID is required.');if(!(Number(data.amount)>0))throw new Error('Deposit amount must be greater than zero.');if(typeof apiAddDeposit==='function')return apiAddDeposit(data);throw new Error('apiAddDeposit() is not available.');}
function controlCenterCreateInvoice(data){if(!data||!data.studentId)throw new Error('Student ID is required.');if(typeof apiCreateInvoice==='function')return apiCreateInvoice(data);throw new Error('apiCreateInvoice() is not available.');}
function controlCenterSendInvoice(data){if(!data||!data.invoiceId)throw new Error('Invoice ID is required.');if(typeof apiSendInvoice==='function')return apiSendInvoice(data);throw new Error('apiSendInvoice() is not available.');}
function controlCenterMenu_(){SpreadsheetApp.getUi().createMenu('Control Center').addItem('Open Master Panel','controlCenterOpen').addToUi();}
function onOpen(){controlCenterMenu_();}
