/** TAREK RIJSCHOOL — SINGLE FILE MASTER CONTROL CENTER */
const TAREK_SINGLE_FILE_VERSION='2026-09-18';


/* ===== ControlCenter.gs ===== */
/* TAREK RIJSCHOOL — Google Sheets Master Control Center. */
var CONTROL_CENTER_SHEETS={students:'Students',lessons:'Lessons',trainers:'Trainers',trainerSchedule:'TrainerSchedule',packages:'Packages',invoices:'Invoices',payments:'Wallet',notifications:'Notifications',settings:'SchoolSettings',controlSettings:'ControlSettings',expenseCategories:'ExpenseCategories',expenses:'Expenses',availability:'Availability',documents:'Documents',audit:'AuditLogs'};
var CONTROL_CENTER_IDS={students:{header:'Student ID',prefix:'ST-',width:6},lessons:{header:'Lesson ID',prefix:'LES-',width:6},trainers:{header:'Trainer ID',prefix:'TR-',width:6},packages:{header:'id',prefix:'PKG-',width:6},invoices:{header:'Invoice ID',prefix:'INV-'+new Date().getFullYear()+'-',width:3},payments:{header:'Transaction ID',prefix:'TX-',width:6},notifications:{header:'Notification ID',prefix:'NOT-',width:6},controlSettings:{header:'Key',prefix:'CFG-',width:6},expenseCategories:{header:'Category ID',prefix:'EXP-CAT-',width:4},expenses:{header:'Expense ID',prefix:'EXP-',width:6},availability:{header:'Availability ID',prefix:'AVL-',width:6},documents:{header:'Document ID',prefix:'DOC-',width:6}};
function controlCenterHtml(){return HtmlService.createHtmlOutput('<h2>TAREK RIJSCHOOL</h2><p>Use the Dashboard sheet and TAREK RIJSCHOOL menu.</p>').setTitle('TAREK RIJSCHOOL')}
function controlCenterOpen(){SpreadsheetApp.getActive().setActiveSheet(SpreadsheetApp.getActive().getSheetByName('Dashboard'));}
function controlCenterGetData(){var ss=SpreadsheetApp.getActiveSpreadsheet();return{generatedAt:new Date().toISOString(),dashboard:controlCenterDashboard_(ss),students:controlCenterRows_(ss,'Students'),lessons:controlCenterRows_(ss,'Lessons'),trainers:controlCenterRows_(ss,'Trainers'),trainerSchedule:controlCenterRows_(ss,'TrainerSchedule'),packages:controlCenterRows_(ss,'Packages'),invoices:controlCenterRows_(ss,'Invoices'),payments:controlCenterRows_(ss,'Wallet'),notifications:controlCenterRows_(ss,'Notifications'),settings:controlCenterRows_(ss,'SchoolSettings'),controlSettings:controlCenterRows_(ss,'ControlSettings'),expenseCategories:controlCenterRows_(ss,'ExpenseCategories'),expenses:controlCenterRows_(ss,'Expenses'),availability:controlCenterRows_(ss,'Availability'),documents:controlCenterRows_(ss,'Documents'),audit:controlCenterRows_(ss,'AuditLogs').slice(-100).reverse(),schemas:controlCenterSchemas_(ss)}}
function controlCenterSchemas_(ss){var out={};Object.keys(CONTROL_CENTER_SHEETS).forEach(function(k){var sh=ss.getSheetByName(CONTROL_CENTER_SHEETS[k]);out[k]=sh&&sh.getLastColumn()?sh.getRange(1,1,1,sh.getLastColumn()).getDisplayValues()[0]:[]});return out}
function controlCenterDashboard_(ss){var students=controlCenterRows_(ss,'Students'),lessons=controlCenterRows_(ss,'Lessons'),payments=controlCenterRows_(ss,'Wallet'),invoices=controlCenterRows_(ss,'Invoices'),today=controlCenterDateKey_(new Date()),month=Utilities.formatDate(new Date(),Session.getScriptTimeZone(),'yyyy-MM');var active=students.filter(function(r){return String(r.status||'').toLowerCase()==='active'}).length;var td=lessons.filter(function(r){return controlCenterDateKey_(r.date)===today}).length;var upcoming=lessons.filter(function(r){var d=controlCenterDateKey_(r.date);return d&&d>=today&&String(r.status||'').toLowerCase()!=='cancelled'}).length;var revenue=payments.reduce(function(sum,r){var d=controlCenterDateKey_(r.date),a=Number(r.amount||0),t=String(r.type||'').toLowerCase();return d.indexOf(month)===0&&a>0&&t!=='payment'?sum+a:sum},0);var due=students.reduce(function(sum,r){var b=Number(r.balance||0);return b<0?sum+Math.abs(b):sum},0);return{totalStudents:students.length,activeStudents:active,todayLessons:td,upcomingLessons:upcoming,monthlyRevenue:revenue,outstandingBalance:due,totalInvoices:invoices.length,lastSync:new Date().toISOString()}}
function controlCenterRows_(ss,name){var sh=ss.getSheetByName(name);if(!sh||sh.getLastRow()<1||sh.getLastColumn()<1)return[];var values=sh.getDataRange().getValues(),headers=values[0].map(function(h){return String(h||'').trim()});return values.slice(1).filter(function(row){return row.some(function(v){return v!==''})}).map(function(row,i){var o={_row:i+2,_sheet:name};headers.forEach(function(h,j){if(h)o[h]=controlCenterSerializable_(row[j])});o.id=controlCenterFirst_(o,['ID','Id','id','Student ID','Trainer ID','Lesson ID','Invoice ID','Transaction ID','Notification ID']);o.studentId=controlCenterFirst_(o,['Student ID']);o.name=controlCenterFirst_(o,['Name','Student Name','Trainer Name']);o.email=controlCenterFirst_(o,['Email','Student Email']);o.phone=controlCenterFirst_(o,['Phone']);o.date=controlCenterFirst_(o,['Date']);o.time=controlCenterFirst_(o,['Time']);o.status=controlCenterFirst_(o,['Status','Read Status','isActive']);o.amount=controlCenterFirst_(o,['Amount (€)','Price (€)','price']);o.balance=controlCenterFirst_(o,['Balance (€)']);o.type=controlCenterFirst_(o,['Type']);o.desc=controlCenterFirst_(o,['Description','Message']);return o})}
function controlCenterSerializable_(v){return v instanceof Date?Utilities.formatDate(v,Session.getScriptTimeZone(),'yyyy-MM-dd HH:mm:ss'):v}function controlCenterFirst_(o,keys){for(var i=0;i<keys.length;i++)if(Object.prototype.hasOwnProperty.call(o,keys[i])&&o[keys[i]]!=='')return o[keys[i]];return''}function controlCenterDateKey_(v){if(!v)return'';var d=v instanceof Date?v:new Date(v);if(isNaN(d.getTime()))return String(v).slice(0,10);return Utilities.formatDate(d,Session.getScriptTimeZone(),'yyyy-MM-dd')}
function controlCenterSaveRecord(section,data){if(!data||typeof data!=='object')throw new Error('Record data is required.');if(section==='settings')return controlCenterSaveSettings_(data);if(section==='payments')return controlCenterSavePayment_(data);if(section==='students'&&!String(data['Student ID']||data.id||'').trim())return createStudent({name:data.Name,email:data.Email,phone:data.Phone,dob:data['Date of Birth'],city:data.City,package:data['Current Package'],status:data.Status,theoryStatus:data['Theory Exam Status'],driveFolderId:data['Drive Folder ID']});if(section==='trainers'&&!String(data['Trainer ID']||data.id||'').trim())return createTrainer({name:data.Name,email:data.Email,phone:data.Phone,license:data.License||data['License Class'],vehicle:data.Vehicle||data['Vehicle Details'],rate:data['Rate (€)']||data.Rate});if(section==='lessons'&&!String(data['Lesson ID']||data.id||'').trim())return TarekCreateLesson_({studentId:data['Student ID'],trainerName:data['Trainer Name']||data['Trainer ID'],date:data.Date,time:data.Time,duration:data['Duration (h)'],price:data['Price (€)'],pickup:data['Pickup Location'],notes:data['Instructor Notes']});if(section==='invoices'&&!String(data['Invoice ID']||data.id||'').trim())return apiCreateInvoice({studentId:data['Student ID'],amount:data['Amount (€)'],description:data.Description});var cfg=controlCenterSectionConfig_(section),ss=SpreadsheetApp.getActiveSpreadsheet(),sh=ss.getSheetByName(cfg.sheet);if(!sh)throw new Error(cfg.sheet+' sheet is missing.');var headers=sh.getRange(1,1,1,sh.getLastColumn()).getDisplayValues()[0].map(function(h){return String(h||'').trim()}),id=String(data[cfg.idHeader]||data.id||'').trim();if(!id)id=controlCenterNextId_(sh,cfg.idHeader,cfg.prefix,cfg.width);data[cfg.idHeader]=id;controlCenterValidateRecord_(section,data);var found=controlCenterFindRowById_(sh,headers,cfg.idHeader,id),previous=found.row>1?sh.getRange(found.row,1,1,headers.length).getDisplayValues()[0]:null,values=headers.map(function(h){return controlCenterSanitizeCell_(Object.prototype.hasOwnProperty.call(data,h)?data[h]:'')});if(found.row>1)sh.getRange(found.row,1,1,headers.length).setValues([values]);else sh.appendRow(values);controlCenterAudit_((found.row>1?'Update ':'Create ')+section,id,previous?JSON.stringify(previous):'',JSON.stringify(values));return{success:true,id:id,created:found.row<2}}
function controlCenterSavePayment_(data){var id=String(data['Transaction ID']||data.id||'').trim();if(id){return controlCenterSaveGenericPayment_(data)}var sid=String(data['Student ID']||'').trim(),amount=Number(data['Amount (€)']),type=String(data.Type||'deposit').toLowerCase(),desc=String(data.Description||'Balance Top-Up');if(!sid)throw new Error('Student ID is required.');if(!(amount>0))throw new Error('Amount must be greater than zero.');if(type!=='deposit')throw new Error('New manual wallet entries must be deposits. Lesson payments are created by lesson operations.');var ss=SpreadsheetApp.getActiveSpreadsheet(),student=controlCenterFindStudent_(ss,sid),sh=ss.getSheetByName('Wallet'),tx='TX-'+Date.now(),now=new Date();sh.appendRow([tx,sid,student.name,Utilities.formatDate(now,Session.getScriptTimeZone(),'yyyy-MM-dd'),'deposit',amount,desc,'','']);controlCenterRebuildBalance_(ss,sid);controlCenterAudit_('Add deposit',tx,'',JSON.stringify({studentId:sid,amount:amount,description:desc}));return{success:true,id:tx,created:true}}
function controlCenterSaveGenericPayment_(data){var cfg=controlCenterSectionConfig_('payments'),sh=SpreadsheetApp.getActiveSpreadsheet().getSheetByName(cfg.sheet),headers=sh.getRange(1,1,1,sh.getLastColumn()).getDisplayValues()[0].map(String),id=String(data['Transaction ID']||data.id),found=controlCenterFindRowById_(sh,headers,cfg.idHeader,id);if(found.row<2)throw new Error('Wallet transaction not found.');var old=sh.getRange(found.row,1,1,headers.length).getDisplayValues()[0],sid=String(data['Student ID']||old[1]),values=headers.map(function(h,i){return controlCenterSanitizeCell_(Object.prototype.hasOwnProperty.call(data,h)?data[h]:old[i])});sh.getRange(found.row,1,1,headers.length).setValues([values]);controlCenterRebuildBalance_(SpreadsheetApp.getActiveSpreadsheet(),sid);controlCenterAudit_('Update payment',id,JSON.stringify(old),JSON.stringify(values));return{success:true,id:id,created:false}}
function controlCenterFindStudent_(ss,id){var rows=controlCenterRows_(ss,'Students');for(var i=0;i<rows.length;i++)if(String(rows[i]['Student ID'])===String(id))return{name:rows[i].Name||'',row:rows[i]._row};throw new Error('Student was not found.')}
function controlCenterRebuildBalance_(ss,id){var tx=controlCenterRows_(ss,'Wallet'),bal=0;tx.forEach(function(r){if(String(r['Student ID'])!==String(id))return;var a=Number(r['Amount (€)'])||0,t=String(r.Type||'').toLowerCase();if(t==='deposit')bal+=a;else if(t==='payment')bal-=a});var sh=ss.getSheetByName('Students'),headers=sh.getRange(1,1,1,sh.getLastColumn()).getDisplayValues()[0],idCol=headers.indexOf('Student ID'),balCol=headers.indexOf('Balance (€)');if(idCol<0||balCol<0)throw new Error('Students wallet columns are missing.');var vals=sh.getRange(2,idCol+1,Math.max(sh.getLastRow()-1,1),1).getDisplayValues();for(var i=0;i<vals.length;i++)if(String(vals[i][0])===String(id)){sh.getRange(i+2,balCol+1).setValue(bal);return bal}throw new Error('Student was not found while rebuilding balance.')}
function controlCenterDeleteRecord(section,id){if(['settings'].indexOf(section)!==-1)throw new Error('Settings cannot be deleted.');var cfg=controlCenterSectionConfig_(section),ss=SpreadsheetApp.getActiveSpreadsheet(),sh=ss.getSheetByName(cfg.sheet),headers=sh.getRange(1,1,1,sh.getLastColumn()).getDisplayValues()[0].map(function(h){return String(h||'').trim()}),found=controlCenterFindRowById_(sh,headers,cfg.idHeader,id);if(found.row<2)throw new Error('Record not found.');var old=sh.getRange(found.row,1,1,headers.length).getDisplayValues()[0],sid=section==='payments'?String(old[1]||''):'';sh.deleteRow(found.row);if(sid)controlCenterRebuildBalance_(ss,sid);controlCenterAudit_('Delete '+section,String(id),JSON.stringify(old),'DELETED');return{success:true,id:id}}
function controlCenterSaveSettings_(data){var sh=SpreadsheetApp.getActiveSpreadsheet().getSheetByName('SchoolSettings');if(!sh)throw new Error('SchoolSettings sheet is missing.');var headers=sh.getRange(1,1,1,sh.getLastColumn()).getDisplayValues()[0].map(function(h){return String(h||'').trim()}),old=sh.getLastRow()>=2?sh.getRange(2,1,1,headers.length).getDisplayValues()[0]:headers.map(function(){return''}),next=headers.map(function(h,i){return Object.prototype.hasOwnProperty.call(data,h)?controlCenterSanitizeCell_(data[h]):old[i]});if(sh.getLastRow()>=2)sh.getRange(2,1,1,headers.length).setValues([next]);else sh.appendRow(next);controlCenterAudit_('Update settings','SchoolSettings',JSON.stringify(old),JSON.stringify(next));return{success:true,id:'SchoolSettings'}}
function controlCenterSectionConfig_(s){var x=CONTROL_CENTER_IDS[s],sheet=CONTROL_CENTER_SHEETS[s];if(!x||!sheet)throw new Error('Unsupported Control Center section: '+s);return{sheet:sheet,idHeader:x.header,prefix:x.prefix,width:x.width}}
function controlCenterFindRowById_(sh,headers,h,id){var idx=headers.indexOf(h);if(idx<0)throw new Error('Required ID column "'+h+'" is missing from '+sh.getName()+'.');if(sh.getLastRow()<2)return{row:-1,index:idx};var ids=sh.getRange(2,idx+1,sh.getLastRow()-1,1).getDisplayValues();for(var i=0;i<ids.length;i++)if(String(ids[i][0])===String(id))return{row:i+2,index:idx};return{row:-1,index:idx}}
function controlCenterNextId_(sh,h,prefix,width){var headers=sh.getRange(1,1,1,sh.getLastColumn()).getDisplayValues()[0],idx=headers.indexOf(h);if(idx<0)throw new Error('Required ID column "'+h+'" is missing.');var max=0;if(sh.getLastRow()>=2)sh.getRange(2,idx+1,sh.getLastRow()-1,1).getDisplayValues().forEach(function(r){var v=String(r[0]||'');if(v.indexOf(prefix)===0){var n=parseInt(v.slice(prefix.length),10);if(!isNaN(n)&&n>max)max=n}});return prefix+String(max+1).padStart(width,'0')}
function controlCenterValidateRecord_(s,d){function req(h,l){if(!String(d[h]||'').trim())throw new Error((l||h)+' is required.')}if(s==='students'){req('Name');req('Email')}if(s==='lessons'){req('Student ID');req('Date');req('Time')}if(s==='trainers'){req('Name');if(!(Number(d['Rate (€)'])>0))throw new Error('Trainer hourly rate must be greater than zero.')}if(s==='invoices'){req('Student ID');req('Student Name')}if(s==='packages')req('name','Package name');if(s==='notifications'){req('Title');req('Message')}if(s==='expenseCategories'){req('Name')}if(s==='expenses'){req('Date');req('Category Name');if(!(Number(d['Amount (€)'])>0))throw new Error('Expense amount must be greater than zero.')}if(s==='availability'){req('Trainer ID');req('Date');req('Start Time');req('End Time')}if(s==='documents'){req('Owner Type');req('Owner ID');req('Document Type');req('Drive URL')}}
function controlCenterSanitizeCell_(v){if(v===null||typeof v==='undefined')return'';if(typeof v==='number'||typeof v==='boolean')return v;var s=String(v);if(/^[=+@]/.test(s)||(/^-/.test(s)&&!/^-?\d+(\.\d+)?$/.test(s)))return"'"+s;return s}
function controlCenterAudit_(action,target,oldv,newv){var sh=SpreadsheetApp.getActiveSpreadsheet().getSheetByName('AuditLogs');if(!sh)return;var headers=sh.getRange(1,1,1,sh.getLastColumn()).getDisplayValues()[0],now=new Date(),v={'Audit ID':'AUD-'+Date.now(),'User ID':'ADMIN-01','User Name':'System Administrator','User Role':'Admin','Action':action,'Changed By':'Master Control Center','Date':Utilities.formatDate(now,Session.getScriptTimeZone(),'yyyy-MM-dd'),'Time':Utilities.formatDate(now,Session.getScriptTimeZone(),'HH:mm:ss'),'Time Zone':Session.getScriptTimeZone(),'IP Address':'','Device / Browser':'','Target Record':target,'Previous Value':oldv,'New Value':newv,'Source':'Google Sheets Master Control Center'};sh.appendRow(headers.map(function(h){return Object.prototype.hasOwnProperty.call(v,h)?v[h]:''}))}
function controlCenterMenu_(){SpreadsheetApp.getUi().createMenu('🚗 TAREK RIJSCHOOL').addItem('Open Master Control Center','controlCenterOpen').addItem('Refresh Control Center Data','controlCenterRefresh_').addToUi()}function controlCenterRefresh_(){SpreadsheetApp.getActiveSpreadsheet().toast('Control Center data refreshed.','TAREK RIJSCHOOL',3)}function onOpen(){controlCenterMenu_()}

/* Dashboard interaction bridge: bound-sheet sidebar forms and language switcher. */
function onSelectionChange(e){try{var r=e&&e.range;if(!r||r.getSheet().getName()!=='Dashboard')return;var row=r.getRow(),col=r.getColumn();if(row<=4&&col>=27&&col<=28){var lang=String(r.getDisplayValue()||'').trim().toUpperCase();if(['EN','NL','AR'].indexOf(lang)>=0)controlCenterSetDashboardLanguage(lang);return}if(col>4)return;var map=[[6,7,'dashboard'],[8,9,'students'],[10,11,'lessons'],[12,13,'trainers'],[14,15,'payments'],[16,17,'invoices'],[18,19,'packages'],[20,21,'notifications'],[22,23,'audit'],[24,25,'settings']];for(var i=0;i<map.length;i++)if(row>=map[i][0]&&row<=map[i][1]){controlCenterSidebarAction_(map[i][2]);return}}catch(err){}}
function controlCenterSidebarAction_(section){if(section==='dashboard'){SpreadsheetApp.getActive().setActiveSheet(SpreadsheetApp.getActive().getSheetByName('Dashboard'));return}if(section==='students'){menuAddStudent();return}if(section==='lessons'){menuAddLesson();return}if(section==='trainers'){menuAddTrainer();return}if(section==='payments'){menuAddDeposit();return}if(section==='packages'){controlCenterOpenSection_('packages');return}if(section==='invoices'){controlCenterOpenSection_('invoices');return}if(section==='notifications'){controlCenterOpenSection_('notifications');return}if(section==='audit'){controlCenterOpenSection_('audit');return}if(section==='settings'){controlCenterOpenSection_('settings');return}var ss=SpreadsheetApp.getActive(),sh=ss.getSheetByName(CONTROL_CENTER_SHEETS[section]);if(sh)ss.setActiveSheet(sh);else controlCenterOpen()}
function controlCenterSetDashboardLanguage(lang){var sh=SpreadsheetApp.getActive().getSheetByName('Dashboard');if(!sh)throw new Error('Dashboard sheet is missing.');var t={EN:['Dashboard','Students','Lessons','Trainers','Finance','Invoices','Packages','Notifications','Reports','Settings','MASTER CONTROL CENTER','Students  •  Lessons  •  Trainers  •  Finance  •  Reports  •  Settings'],NL:['Dashboard','Leerlingen','Lessen','Instructeurs','Financiën','Facturen','Pakketten','Meldingen','Rapporten','Instellingen','MASTER CONTROL CENTER','Leerlingen  •  Lessen  •  Instructeurs  •  Financiën  •  Rapporten  •  Instellingen'],AR:['لوحة التحكم','الطلاب','الدروس','المدربون','المالية','الفواتير','الباقات','الإشعارات','التقارير','الإعدادات','مركز التحكم الرئيسي','الطلاب  •  الدروس  •  المدربون  •  المالية  •  التقارير  •  الإعدادات']}[lang];if(!t)throw new Error('Unsupported language.');var rows=[6,8,10,12,14,16,18,20,22,24],icons=['⌂  ','👤  ','📅  ','👥  ','€  ','📄  ','▦  ','🔔  ','▥  ','⚙  '];for(var i=0;i<rows.length;i++)sh.getRange(rows[i],1).setValue(icons[i]+t[i]);sh.getRange(1,5).setValue(t[10]+'\n'+t[11]);sh.getRange(1,27).setValue(lang);SpreadsheetApp.getActive().toast(lang==='AR'?'تم تغيير لغة لوحة التحكم':lang==='NL'?'Taal van het dashboard gewijzigd':'Dashboard language changed','TAREK RIJSCHOOL',2);return{success:true,language:lang}}

function controlCenterOpenSection_(section){var sh=SpreadsheetApp.getActive().getSheetByName(CONTROL_CENTER_SHEETS[section]);if(sh)SpreadsheetApp.getActive().setActiveSheet(sh)}
function apiGetStudentsAndTrainers(){var ss=SpreadsheetApp.getActive(),s=controlCenterRows_(ss,'Students'),t=controlCenterRows_(ss,'Trainers');return{students:s.map(x=>({id:x['Student ID'],name:x.Name,balance:Number(x['Balance (€)'])||0,status:x.Status})),trainers:t.map(x=>({id:x['Trainer ID'],name:x.Name,rate:Number(x['Rate (€)'])||0,status:x.Status}))}}
function apiAddWalletDeposit(params){return controlCenterSavePayment_({'Student ID':params.studentId,'Type':'deposit','Amount (€)':Number(params.amount),'Description':String(params.description||'Deposit')})}


/* ===== Students.gs ===== */
/** TAREK RIJSCHOOL — Student Operations. */
function studentHeaderMap_(sheet){if(!sheet||sheet.getLastRow()<1)throw new Error('Students sheet is missing or empty.');const h=sheet.getRange(1,1,1,sheet.getLastColumn()).getValues()[0],m={};h.forEach((x,i)=>{const k=String(x||'').trim().toLowerCase();if(k)m[k]=i});return m}
function studentCol_(m,n,r){for(const x of n){const i=m[String(x).toLowerCase()];if(i!==undefined)return i}if(r)throw new Error('Required Students column is missing: '+n[0]);return-1}
function apiGetStudentDashboard(identifier){if(!identifier)throw new Error('Student email or ID is required.');const ss=SpreadsheetApp.getActiveSpreadsheet(),s=ss.getSheetByName('Students'),l=ss.getSheetByName('Lessons'),w=ss.getSheetByName('Wallet');if(!s||!l||!w)throw new Error('Required student sheets are missing.');const m=studentHeaderMap_(s),cId=studentCol_(m,['student id'],true),cName=studentCol_(m,['name'],true),cEmail=studentCol_(m,['email'],true),cPhone=studentCol_(m,['phone'],false),cDob=studentCol_(m,['date of birth'],false),cCity=studentCol_(m,['city'],false),cPackage=studentCol_(m,['current package'],false),cBalance=studentCol_(m,['balance (€)'],false),cReady=studentCol_(m,['exam readiness (%)'],false),cStatus=studentCol_(m,['status'],false);const rows=s.getDataRange().getValues();let student=null;for(let i=1;i<rows.length;i++){if(String(rows[i][cId]||'')===String(identifier)||String(rows[i][cEmail]||'').toLowerCase()===String(identifier).toLowerCase()){student={id:rows[i][cId],name:rows[i][cName],email:rows[i][cEmail],phone:cPhone>=0?rows[i][cPhone]:'',dob:cDob>=0?rows[i][cDob]:'',city:cCity>=0?rows[i][cCity]:'',package:cPackage>=0?rows[i][cPackage]:'',balance:cBalance>=0?Number(rows[i][cBalance])||0:0,readiness:cReady>=0?Number(rows[i][cReady])||0:0,status:cStatus>=0?rows[i][cStatus]:''};break}}if(!student)throw new Error('Student was not found.');const lessons=l.getDataRange().getValues(),bookings=[];for(let i=1;i<lessons.length;i++)if(String(lessons[i][1]||'')===String(student.id))bookings.push({bookingId:lessons[i][0],studentId:lessons[i][1],studentName:lessons[i][2],trainerName:lessons[i][3],date:lessons[i][4],time:lessons[i][5],duration:Number(lessons[i][6]),price:Number(lessons[i][7]),pickup:lessons[i][8],status:lessons[i][9]});const tx=w.getDataRange().getValues(),transactions=[];for(let i=1;i<tx.length;i++)if(String(tx[i][1]||'')===String(student.id))transactions.push({txId:tx[i][0],date:tx[i][3],type:tx[i][4],amount:Number(tx[i][5])||0,desc:tx[i][6]});return{student,bookings,transactions}}
function createStudent(params){const ss=SpreadsheetApp.getActiveSpreadsheet(),sheet=ss.getSheetByName('Students');if(!sheet)throw new Error('Students sheet is missing.');const m=studentHeaderMap_(sheet),name=String(params&&params.name||'').trim(),email=String(params&&params.email||'').trim();if(!name)throw new Error('Student name is required.');if(!email)throw new Error('Student email is required.');const existing=sheet.getDataRange().getValues();for(let i=1;i<existing.length;i++)if(String(existing[i][m['email']]||'').toLowerCase()===email.toLowerCase())throw new Error('A student with this email already exists.');const id='ST-'+Date.now(),row=new Array(sheet.getLastColumn()).fill(''),put=(k,v)=>{if(m[k]!==undefined)row[m[k]]=v};put('student id',id);put('name',name);put('email',email);put('phone',String(params.phone||''));put('date of birth',String(params.dob||params['Date of Birth']||''));put('city',String(params.city||''));put('current package',String(params.package||params['Current Package']||''));put('balance (€)',Number(params.balance||0));put('exam readiness (%)',Number(params.readiness||0));put('status',String(params.status||'active'));put('theory exam status',String(params.theoryStatus||''));put('drive folder id',String(params.driveFolderId||''));sheet.appendRow(row);if(typeof writeAdminLog==='function')writeAdminLog('Create Student','Master Control Center','Registered '+name+' ('+id+')');return{success:true,studentId:id,name}}
function menuAddStudent(){TarekMasterAddStudent()}


/* ===== Trainers.gs ===== */
/** TAREK RIJSCHOOL — Trainer Operations. */
function apiGetTrainerDashboard(identifier){if(!identifier)throw new Error('Trainer email or ID is required.');const ss=SpreadsheetApp.getActiveSpreadsheet(),t=ss.getSheetByName('Trainers'),l=ss.getSheetByName('Lessons');if(!t||!l)throw new Error('Required trainer sheets are missing.');const rows=t.getDataRange().getValues();let trainer=null;for(let i=1;i<rows.length;i++)if(String(rows[i][0]||'')===String(identifier)||String(rows[i][2]||'').toLowerCase()===String(identifier).toLowerCase()){trainer={id:rows[i][0],name:rows[i][1],email:rows[i][2],phone:rows[i][3],license:rows[i][4],vehicle:rows[i][5],rate:Number(rows[i][6])||0,status:rows[i][7]};break}if(!trainer)throw new Error('Trainer profile not found.');const lessons=l.getDataRange().getValues(),bookings=[];for(let i=1;i<lessons.length;i++)if(String(lessons[i][3]||'')===String(trainer.name))bookings.push({bookingId:lessons[i][0],studentId:lessons[i][1],studentName:lessons[i][2],date:lessons[i][4],time:lessons[i][5],duration:Number(lessons[i][6]),price:Number(lessons[i][7]),pickup:lessons[i][8],status:lessons[i][9]});return{trainer,bookings}}
function createTrainer(params){const sh=SpreadsheetApp.getActiveSpreadsheet().getSheetByName('Trainers');if(!sh)throw new Error('Trainers sheet is missing.');const name=String(params&&params.name||'').trim(),email=String(params&&params.email||'').trim(),phone=String(params&&params.phone||'').trim(),license=String(params&&params.license||'').trim(),vehicle=String(params&&params.vehicle||'').trim(),rate=Number(params&&params.rate);if(!name||!email)throw new Error('Trainer name and email are required.');if(!(rate>0))throw new Error('Trainer hourly rate must be greater than zero.');const rows=sh.getDataRange().getValues();for(let i=1;i<rows.length;i++)if(String(rows[i][2]||'').toLowerCase()===email.toLowerCase())throw new Error('A trainer with this email already exists.');const id='TR-'+Date.now();sh.appendRow([id,name,email,phone,license,vehicle,rate,'active']);if(typeof writeAdminLog==='function')writeAdminLog('Create Trainer','Master Control Center','Registered '+name+' ('+id+')');return{success:true,trainerId:id,name}}
function updateTrainerSchedule(params){const sh=SpreadsheetApp.getActiveSpreadsheet().getSheetByName('TrainerSchedule');if(!sh)throw new Error('TrainerSchedule sheet is missing.');const id=String(params&&params.trainerId||'').trim(),name=String(params&&params.trainerName||'').trim(),day=String(params&&params.dayOfWeek||'').trim(),start=String(params&&params.startTime||'').trim(),end=String(params&&params.endTime||'').trim(),available=params&&params.isAvailable!==undefined?String(params.isAvailable).toUpperCase():'TRUE';if(!id||!name||!day||!start||!end)throw new Error('Complete trainer schedule details are required.');const rows=sh.getDataRange().getValues();for(let i=1;i<rows.length;i++)if(String(rows[i][0])===id&&String(rows[i][2]).toLowerCase()===day.toLowerCase()){sh.getRange(i+1,2,1,5).setValues([[name,day,start,end,available]]);return{success:true}}sh.appendRow([id,name,day,start,end,available]);return{success:true}}
function menuAddTrainer(){TarekMasterAddTrainer()}


/* ===== Wallet.gs ===== */
/** TAREK RIJSCHOOL — Digital Wallet Operations. */
function apiAddDeposit(params){const sid=String(params&&params.studentId||'').trim(),amount=Number(params&&params.amount),desc=String(params&&params.description||'Balance Top-Up').trim();if(!sid)throw new Error('Student ID is required.');if(!(amount>0))throw new Error('Deposit amount must be greater than zero.');const student=apiGetStudentDashboard(sid).student;writeTransactionRecord(student.id,student.name,'deposit',amount,desc);rebuildStudentBalance(student.id);const updated=apiGetStudentDashboard(sid).student;if(updated.email&&typeof sendResponsiveEmail==='function')sendResponsiveEmail(updated.email,updated.name,'deposit',{amount,paymentMethod:desc,newBalance:updated.balance});if(typeof writeAdminLog==='function')writeAdminLog('Add Deposit API','Master Control Center','Credited '+student.name+' with €'+amount);return{txId:apiLastWalletTransactionId_(),newBalance:updated.balance}}
function apiAddWalletDeposit(params){return apiAddDeposit(params)}
function apiLastWalletTransactionId_(){const sh=SpreadsheetApp.getActiveSpreadsheet().getSheetByName('Wallet');return sh&&sh.getLastRow()>1?String(sh.getRange(sh.getLastRow(),1).getValue()||''):''}
function writeTransactionRecord(studentId,studentName,type,amount,desc){const sh=SpreadsheetApp.getActiveSpreadsheet().getSheetByName('Wallet');if(!sh)throw new Error('Wallet sheet is missing.');const id='TX-'+Date.now(),now=new Date();sh.appendRow([id,studentId,studentName,Utilities.formatDate(now,Session.getScriptTimeZone(),'yyyy-MM-dd'),String(type||'').toLowerCase(),Number(amount)||0,String(desc||''),'','']);return id}
function rebuildStudentBalance(studentId){const ss=SpreadsheetApp.getActiveSpreadsheet(),w=ss.getSheetByName('Wallet'),s=ss.getSheetByName('Students');if(!w||!s)throw new Error('Required wallet sheets are missing.');const tx=w.getDataRange().getValues();let bal=0;for(let i=1;i<tx.length;i++){if(String(tx[i][1]||'')!==String(studentId))continue;const t=String(tx[i][4]||'').toLowerCase(),v=Number(tx[i][5])||0;if(t==='deposit')bal+=v;else if(t==='payment')bal-=v}const rows=s.getDataRange().getValues();for(let i=1;i<rows.length;i++)if(String(rows[i][0]||'')===String(studentId)){s.getRange(i+1,8).setValue(bal);return bal}throw new Error('Student was not found while rebuilding wallet balance.')}
function addDeposit(params){return apiAddDeposit(params)}
function menuAddDeposit(){TarekMasterAddDeposit()}


/* ===== Invoices.gs ===== */
/** TAREK RIJSCHOOL — Invoice Operations. */
function apiCreateInvoice(params){const ss=SpreadsheetApp.getActiveSpreadsheet(),inv=ss.getSheetByName('Invoices'),lessons=ss.getSheetByName('Lessons');if(!inv||!lessons)throw new Error('Required invoice sheets are missing.');const sid=String(params&&params.studentId||'').trim(),description=String(params&&params.description||'Driving lessons').trim(),list=String(params&&params.bookingsList||'').trim();if(!sid)throw new Error('Student ID is required.');const student=apiGetStudentDashboard(sid).student;let amount=Number(params&&params.amount)||0;if(!amount&&list){const rows=lessons.getDataRange().getValues();list.split(',').forEach(id=>{for(let i=1;i<rows.length;i++)if(String(rows[i][0]||'')===id.trim()){amount+=Number(rows[i][7])||0;break}})}if(!(amount>0))throw new Error('Invoice amount must be greater than zero.');const id='INV-'+Utilities.formatDate(new Date(),Session.getScriptTimeZone(),'yyyyMMdd')+'-'+Date.now(),date=Utilities.formatDate(new Date(),Session.getScriptTimeZone(),'yyyy-MM-dd');const html=getInvoicePdfHtml_({invoiceId:id,invoiceDate:date,studentName:student.name,studentId:student.id,description,grandTotal:amount}),blob=HtmlService.createHtmlOutput(html).getBlob().getAs(MimeType.PDF).setName(id+'.pdf'),file=DriveApp.createFile(blob);inv.appendRow([id,student.id,student.name,student.email,amount,date,description,'issued',file.getId(),file.getUrl()]);if(typeof writeAdminLog==='function')writeAdminLog('Create Invoice API','Master Control Center','Generated '+id+' for '+student.name);return{invoiceId:id,grandTotal:amount,pdfUrl:file.getUrl()}}
function apiSendInvoice(params){const id=String(params&&params.invoiceId||'').trim();if(!id)throw new Error('Invoice ID is required.');const sh=SpreadsheetApp.getActiveSpreadsheet().getSheetByName('Invoices');if(!sh)throw new Error('Invoices sheet is missing.');const rows=sh.getDataRange().getValues();let x=null,rowNo=0;for(let i=1;i<rows.length;i++)if(String(rows[i][0]||'')===id){x={studentId:rows[i][1],name:rows[i][2],email:rows[i][3],amount:Number(rows[i][4])||0,date:rows[i][5],description:rows[i][6],status:rows[i][7],fileId:rows[i][8],url:rows[i][9]};rowNo=i+1;break}if(!x)throw new Error('Invoice '+id+' does not exist.');if(!x.email)throw new Error('Student email is missing.');if(!x.fileId)throw new Error('Invoice PDF file ID is missing.');const pdf=DriveApp.getFileById(String(x.fileId)).getBlob();if(typeof sendResponsiveEmail==='function')sendResponsiveEmail(x.email,x.name,'invoice',{invoiceId:id,description:x.description,grandTotal:x.amount,attachments:[pdf]});else MailApp.sendEmail({to:x.email,subject:'TAREK RIJSCHOOL — Invoice '+id,body:'Dear '+x.name+',\n\nPlease find invoice '+id+' attached.\n\nTAREK RIJSCHOOL',attachments:[pdf]});sh.getRange(rowNo,8).setValue('sent');if(typeof writeAdminLog==='function')writeAdminLog('Send Invoice API','Master Control Center','Sent '+id+' to '+x.email);return{success:true,pdfUrl:x.url}}
function getInvoicePdfHtml_(d){return'<!doctype html><html><head><meta charset="UTF-8"><style>body{font-family:Arial;padding:36px;color:#0f172a}table{width:100%;border-collapse:collapse;margin-top:24px}th,td{border:1px solid #cbd5e1;padding:10px;text-align:left}th{background:#f1f5f9}</style></head><body><h1>TAREK RIJSCHOOL</h1><div>Invoice: '+d.invoiceId+'</div><div>Date: '+d.invoiceDate+'</div><h2>'+d.studentName+' ('+d.studentId+')</h2><table><tr><th>Description</th><th>Total</th></tr><tr><td>'+d.description+'</td><td>€'+Number(d.grandTotal).toFixed(2)+'</td></tr></table></body></html>'}
function createInvoice(params){return apiCreateInvoice(params)}function sendInvoice(params){return apiSendInvoice(params)}


/* ===== Notifications.gs ===== */
/** TAREK RIJSCHOOL — Notifications. */
function menuSendReminder(){const ui=SpreadsheetApp.getUi(),lessonId=ui.prompt('Send Balance Reminder','Enter Lesson ID:',ui.ButtonSet.OK_CANCEL).getResponseText();if(!lessonId)return;const ss=SpreadsheetApp.getActiveSpreadsheet(),sh=ss.getSheetByName('Lessons');if(!sh)throw new Error('Lessons sheet is missing.');const rows=sh.getDataRange().getValues();let sid='';for(let i=1;i<rows.length;i++)if(String(rows[i][0]||'')===lessonId.trim()){sid=String(rows[i][1]||'');break}if(!sid){ui.alert('Error','Lesson not found.',ui.ButtonSet.OK);return}const student=apiGetStudentDashboard(sid).student;if(!student.email)throw new Error('Student email is missing.');const subject='TAREK RIJSCHOOL — Balance reminder',body='Dear '+student.name+',\n\nYour scheduled driving lesson is upcoming. Please top up your wallet balance if needed to keep your lesson administration current.\n\nMet vriendelijke groet,\nTAREK RIJSCHOOL';MailApp.sendEmail(student.email,subject,body);controlCenterCreateNotification_({studentId:student.id,email:student.email,type:'balance_reminder',title:subject,message:body});if(typeof writeAdminLog==='function')writeAdminLog('Send Reminder','Master Control Center','Sent balance reminder to '+student.email);ui.alert('Reminder Dispatched','Notification sent to '+student.email,ui.ButtonSet.OK)}
function controlCenterCreateNotification_(p){const sh=SpreadsheetApp.getActiveSpreadsheet().getSheetByName('Notifications');if(!sh)throw new Error('Notifications sheet is missing.');const id='NOT-'+Date.now(),now=new Date();sh.appendRow([id,'Student',String(p.studentId||''),String(p.email||''),String(p.type||'general'),String(p.title||''),String(p.message||''),Utilities.formatDate(now,Session.getScriptTimeZone(),'yyyy-MM-dd HH:mm:ss'),'Unread']);return{id:id}}

function onOpen(){SpreadsheetApp.getUi().createMenu('🚗 TAREK RIJSCHOOL').addItem('Open Master Control Center','controlCenterOpen').addItem('Refresh Dashboard','TarekMasterRefresh').addSeparator().addItem('Add Student','TarekMasterAddStudent').addItem('Add Lesson','TarekMasterAddLesson').addItem('Add Trainer','TarekMasterAddTrainer').addItem('Add Deposit','TarekMasterAddDeposit').addToUi()}
function TarekMasterRefresh(){SpreadsheetApp.getActive().toast('Live data refreshed.','TAREK RIJSCHOOL',2)}
function TarekMasterPrompt_(t,f){var u=SpreadsheetApp.getUi(),o={};for(var i=0;i<f.length;i++){var r=u.prompt(t,f[i][1],u.ButtonSet.OK_CANCEL);if(r.getSelectedButton()!=u.Button.OK)return null;o[f[i][0]]=r.getResponseText()}return o}
function TarekMasterAddStudent(){var p=TarekMasterPrompt_('Add Student',[['name','Student name'],['email','Email'],['phone','Phone'],['city','City'],['package','Current package']]);if(p)createStudent(p)}
function TarekMasterAddTrainer(){var p=TarekMasterPrompt_('Add Trainer',[['name','Trainer name'],['email','Email'],['phone','Phone'],['license','License'],['vehicle','Vehicle'],['rate','Hourly rate (€)']]);if(p)createTrainer(p)}
function TarekMasterAddDeposit(){var p=TarekMasterPrompt_('Add Deposit',[['studentId','Student ID'],['amount','Amount (€)'],['description','Description']]);if(p)apiAddDeposit(p)}
function TarekMasterAddLesson(){var p=TarekMasterPrompt_('Add Lesson',[['studentId','Student ID'],['trainerName','Trainer name'],['date','Date YYYY-MM-DD'],['time','Time HH:MM'],['duration','Duration hours'],['price','Price (€)'],['pickup','Pickup location']]);if(!p)return;var st=apiGetStudentDashboard(p.studentId).student,sh=SpreadsheetApp.getActive().getSheetByName('Lessons');if(!sh)throw new Error('Lessons sheet is missing.');sh.appendRow(['LES-'+Date.now(),st.id,st.name,p.trainerName,p.date,p.time,Number(p.duration),Number(p.price),p.pickup,'Scheduled','','',''])}

function TarekCreateLesson_(p){var st=apiGetStudentDashboard(p.studentId).student,sh=SpreadsheetApp.getActive().getSheetByName('Lessons');if(!sh)throw new Error('Lessons sheet is missing.');var id='LES-'+Date.now();sh.appendRow([id,st.id,st.name,String(p.trainerName||''),String(p.date||''),String(p.time||''),Number(p.duration)||0,Number(p.price)||0,String(p.pickup||''),'Scheduled','',String(p.notes||''),'']);controlCenterAudit_('Create lesson',id,'',JSON.stringify(p));return{success:true,id:id}}
function TarekBuildDashboard(lang){lang=String(lang||'EN').toUpperCase();var ss=SpreadsheetApp.getActive(),sh=ss.getSheetByName('Dashboard');if(!sh)sh=ss.insertSheet('Dashboard',0);sh.setHiddenGridlines(true);sh.setFrozenRows(4);sh.setFrozenColumns(4);controlCenterSetDashboardLanguage(lang);SpreadsheetApp.flush();return{success:true,language:lang}}
function buildDashboardEn(){return TarekBuildDashboard('EN')}function buildDashboardNl(){return TarekBuildDashboard('NL')}function buildDashboardAr(){return TarekBuildDashboard('AR')}
function TarekWebhookConfig(){var p=PropertiesService.getScriptProperties();return{backendUrl:p.getProperty('BACKEND_URL')||'',webhookSecretConfigured:!!p.getProperty('WEBHOOK_SECRET')}}
function dispatchWebhookChangeEvent(sheetName,changeType,rowId,rowData,studentId){var p=PropertiesService.getScriptProperties(),base=p.getProperty('BACKEND_URL'),secret=p.getProperty('WEBHOOK_SECRET');if(!base||!secret)return{skipped:true};var url=base.replace(/\/$/,'')+'/api/webhooks/sheets-change';var res=UrlFetchApp.fetch(url,{method:'post',contentType:'application/json',payload:JSON.stringify({sheetName:sheetName,changeType:changeType,rowId:rowId,rowData:rowData,studentId:studentId,timestamp:new Date().toISOString(),origin:'sheets-control-center'}),headers:{'X-Webhook-Secret':secret},muteHttpExceptions:true});return{status:res.getResponseCode()}}
